language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.0RC5

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5  LAZ_ENV= INTERNETACCESS=USE_NO_WRAPPER
    - env: LAZ_VER=1.8.0RC5  LAZ_ENV= INTERNETACCESS=USE_SYNAPSE_WRAPPER
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine INTERNETACCESS=USE_WININET_WRAPPER LAZ_OPT="--os=win32 --cpu=i386"
    - env: LAZ_VER=1.8.0RC5  LAZ_ENV=qemu-arm INTERNETACCESS=USE_SYNAPSE_WRAPPER LAZ_OPT="--os=linux --cpu=arm" FPC_OPT="-Parm -Tlinux"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = qemu-arm ]]; then sudo apt-get install libgdk-pixbuf2.0-dev:armhf libx11-dev:armhf libgtk2.0-dev:armhf libcairo-gobject2:armhf; fi
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi
  - mkdir -p import
  - FPCSEARCHPATHS="-Fudata -Fidata -Fuinternet"
  - git clone https://github.com/benibela/flre.git import/flre; cd import/flre; git reset --hard 9910f85305789eafbe7eeb9cbb2c1274e883ae25; cd ../..; echo "-Fuimport/flre/src/" >> ~/.fpc.cfg
  - git clone https://github.com/benibela/rcmdline.git rcmdline
  - if [[ "$INTERNETACCESS" == USE_SYNAPSE_WRAPPER ]]; then svn checkout http://svn.code.sf.net/p/synalist/code/synapse/40/ import/synapse; echo "-Fuimport/synapse" >> ~/.fpc.cfg; fi
  - echo "-d$INTERNETACCESS" >> ~/.fpc.cfg

script:
  - lazbuild $LAZ_OPT --verbose-pkgsearch --add-package internettools.lpk
  - lazbuild $LAZ_OPT --verbose-pkgsearch --add-package internettools_autoupdate.lpk
  - lazbuild $LAZ_OPT --verbose-pkgsearch data/examples/xqueryExampleGUI.lpi
  - lazbuild $LAZ_OPT --verbose-pkgsearch internet/examples/autoupdatetest.lpi
  - fpc -O2 -gl $FPCSEARCHPATHS $FPC_OPT data/tests/tests.lpr 
  - fpc -O2 -gl $FPCSEARCHPATHS $FPC_OPT data/examples/xqueryExample.pas
  - fpc -O2 -gl $FPCSEARCHPATHS -Furcmdline $FPC_OPT data/examples/QT3testsuite.lpr
  - $LAZ_ENV data/tests/tests

notifications:
  email:
    on_failure: change