language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.0RC5

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5  LAZ_ENV= INTERNETACCESS=USE_NO_WRAPPER
    - env: LAZ_VER=1.8.0RC5  LAZ_ENV= INTERNETACCESS=USE_SYNAPSE_WRAPPER

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  - git clone https://github.com/nielsAD/travis-lazarus.git travis-lazarus
  - travis-lazarus/.travis.install.py
  - SEARCHPATHS="-Fudata -Fidata -Fuinternet"
  - git clone https://github.com/benibela/flre.git flre; cd flre; git reset --hard 9910f85305789eafbe7eeb9cbb2c1274e883ae25; cd ..; echo "-Fuflre/src/" >> ~/.fpc.cfg
  - git clone https://github.com/benibela/rcmdline.git rcmdline
  - if [[ "$INTERNETACCESS" == USE_SYNAPSE_WRAPPER ]]; then svn checkout http://svn.code.sf.net/p/synalist/code/synapse/40/ synapse; echo "-Fusynapse" >> ~/.fpc.cfg; fi

script:
  - fpc -O2 -gl $SEARCHPATHS -d$INTERNETACCESS data/tests/tests.lpr 
  - fpc -O2 -gl $SEARCHPATHS -d$INTERNETACCESS data/examples/xqueryExample.pas
  - fpc -O2 -gl $SEARCHPATHS -d$INTERNETACCESS -Furcmdline  data/examples/QT3testsuite.lpr
  - lazbuild $LAZ_OPT internet/examples/autoupdatetest.lpi
  - lazbuild $LAZ_OPT data/examples/xqueryExampleGUI.lpi
  - $LAZ_ENV data/tests/tests

notifications:
  email:
    on_failure: change